/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author ds3dhill
 */
public class BakeryMenu extends javax.swing.JFrame {

    /**
     * Creates new form BakeryMenu
     */
    public BakeryMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Bagels = new javax.swing.JButton();
        Breads = new javax.swing.JButton();
        Pies = new javax.swing.JButton();
        Cakes = new javax.swing.JButton();
        Doughnuts = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 800));
        setPreferredSize(new java.awt.Dimension(1000, 800));
        getContentPane().setLayout(null);

        jPanel1.setMaximumSize(new java.awt.Dimension(1000, 800));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 800));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(954, 0, 1000, 800);

        Bagels.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        Bagels.setForeground(new java.awt.Color(153, 0, 153));
        Bagels.setText("Bagels");
        Bagels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BagelsActionPerformed(evt);
            }
        });
        getContentPane().add(Bagels);
        Bagels.setBounds(110, 140, 180, 43);

        Breads.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        Breads.setForeground(new java.awt.Color(153, 0, 153));
        Breads.setText("Breads");
        Breads.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BreadsActionPerformed(evt);
            }
        });
        getContentPane().add(Breads);
        Breads.setBounds(110, 250, 180, 43);

        Pies.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        Pies.setForeground(new java.awt.Color(153, 0, 153));
        Pies.setText("Pies");
        Pies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PiesActionPerformed(evt);
            }
        });
        getContentPane().add(Pies);
        Pies.setBounds(400, 190, 180, 43);

        Cakes.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        Cakes.setForeground(new java.awt.Color(153, 0, 153));
        Cakes.setText("Cakes");
        Cakes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CakesActionPerformed(evt);
            }
        });
        getContentPane().add(Cakes);
        Cakes.setBounds(400, 310, 180, 43);

        Doughnuts.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        Doughnuts.setForeground(new java.awt.Color(153, 0, 153));
        Doughnuts.setText("Doughnuts");
        Doughnuts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoughnutsActionPerformed(evt);
            }
        });
        getContentPane().add(Doughnuts);
        Doughnuts.setBounds(110, 370, 183, 43);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 153));
        jLabel1.setText("Menu ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(390, 70, 140, 52);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ds3dhill\\Documents\\NetBeansProjects\\GUI testers\\src\\pink_cupcake_wallpaper_2_by_mrskupe.png")); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setMaximumSize(new java.awt.Dimension(1000, 800));
        jLabel2.setMinimumSize(new java.awt.Dimension(1000, 800));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 920, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BagelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BagelsActionPerformed
        // TODO add your handling code here:
         BakeryMenu bakeryScreen = new BakeryMenu ();
            bakeryScreen.setDefaultCloseOperation(bakeryScreen.HIDE_ON_CLOSE );
        //setDefaultCloseOperation(.EXIT_ON_CLOSE);
        Bagels bagel = new Bagels();
        bagel.setVisible (true);   
    }//GEN-LAST:event_BagelsActionPerformed

    private void BreadsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BreadsActionPerformed
        // TODO add your handling code here:
         Breads bread = new Breads();
        bread.setVisible (true); 
    }//GEN-LAST:event_BreadsActionPerformed

    private void DoughnutsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoughnutsActionPerformed
        // TODO add your handling code here:
        Doughnuts doughnut = new Doughnuts();
        doughnut.setVisible (true); 
    }//GEN-LAST:event_DoughnutsActionPerformed

    private void PiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PiesActionPerformed
        // TODO add your handling code here:
        Pies Pie = new Pies();
        Pie.setVisible (true); 
    }//GEN-LAST:event_PiesActionPerformed

    private void CakesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CakesActionPerformed
        // TODO add your handling code here:
        Cakes cake = new Cakes();
        cake.setVisible (true); 
    }//GEN-LAST:event_CakesActionPerformed

    /**
     * @param args the command line arguments
     */
      
               
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BakeryMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BakeryMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BakeryMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BakeryMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BakeryMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bagels;
    private javax.swing.JButton Breads;
    private javax.swing.JButton Cakes;
    private javax.swing.JButton Doughnuts;
    private javax.swing.JButton Pies;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
